### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BryanSWong**
Please look over the files and confirm all is in proper order.

### CODE REVIEW

**Comment by shiraz** [comment]
@BryanSWong 

Please make the following changes:

1) For the Functional Audio player, please change the audio clip. Use some nice music instead of a horse roar. Ensure that the audio clip is at least 30 seconds.

2) For the Non Functional Audio player, please change the "id" such that it has a camel case value. Example, "notWorkingAudio".

3) Add a page header at the top called "Test Media".

**Comment by BryanSWong** [comment]
I have updated the audio file, corrected the id, and have added a header to the page called Test media.

**Comment by shiraz** [comment]
I cant play the mp3 file that is in the code base. Can you please check it out?

**Comment by shiraz** [comment]
Disregard my earlier comment.

**Comment by shiraz** [comment]
Please push to Heroku.

**Pull request merged**
